const services=['Corte','Barba','Combo','Pigmentação','Relaxamento','Pezinho','Luzes','Nevou'];
const times=['09:00','09:30','10:00','10:30','11:00','11:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00'];
const keyBookings='ms-bookings',keyBlocked='ms-blocked-slots',keyDates='ms-blocked-dates';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=d=>new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase();
const bookings=()=>JSON.parse(localStorage.getItem(keyBookings)||'[]');const blocked=()=>JSON.parse(localStorage.getItem(keyBlocked)||'[]');const blockedDates=()=>JSON.parse(localStorage.getItem(keyDates)||'[]');
let selectedDate=today();
document.querySelector('#todayTitle').textContent=fmt(today());document.querySelector('#datePicker').value=selectedDate;
function renderToday(){const list=bookings().filter(x=>x.date===today()&&x.status!=='cancelled').sort((a,b)=>a.time.localeCompare(b.time));const now=new Date().toTimeString().slice(0,5);const next=list.find(x=>x.time>=now)||list[0];document.querySelector('#nextClient').innerHTML=next?`<div class="next-card"><small>PRÓXIMO CLIENTE</small><strong>${next.time} — ${esc(next.name)}</strong><p>${services[next.service]||'Serviço'} · ${esc(next.phone)}</p></div>`:'';document.querySelector('#appointmentList').innerHTML=list.length?list.map(x=>`<div class="appointment"><time>${x.time}</time><div><strong>${esc(x.name)}</strong><small>${services[x.service]||'Serviço'} · ${esc(x.phone)}</small></div><div class="appointment-actions"><button class="done" onclick="setStatus('${x.createdAt}','completed')">Concluir</button><button class="cancel" onclick="setStatus('${x.createdAt}','cancelled')">Cancelar</button></div></div>`).join(''):'<div class="empty">Nenhum agendamento para hoje.</div>'}
function setStatus(id,status){const a=bookings();const x=a.find(v=>v.createdAt===id);if(x)x.status=status;localStorage.setItem(keyBookings,JSON.stringify(a));renderToday();renderDay()}
function renderDay(){const dayBookings=bookings().filter(x=>x.date===selectedDate&&x.status!=='cancelled');const dayBlocked=blocked().filter(x=>x.date===selectedDate).map(x=>x.time);const full=blockedDates().some(x=>x.date===selectedDate);document.querySelector('#dayState').innerHTML=full?'<div class="day-state">Você bloqueou este dia.</div>':'';const dayBtn=document.querySelector('#toggleDay');dayBtn.textContent=full?'DESBLOQUEAR DIA':'BLOQUEAR DIA INTEIRO';dayBtn.classList.toggle('active',full);document.querySelector('#slotList').innerHTML=times.map(t=>{const b=dayBookings.find(x=>x.time===t);const isBlocked=dayBlocked.includes(t)||full;return `<div class="slot ${b?'booked':isBlocked?'blocked':''}"><time>${t}</time><div class="status">${b?`${esc(b.name)} · ${services[b.service]||'Serviço'}`:isBlocked?'BLOQUEADO':'LIVRE'}</div>${!b&&!full?`<button onclick="toggleSlot('${t}')">${isBlocked?'Desbloquear':'Bloquear'}</button>`:''}</div>`}).join('')}
function toggleSlot(time){if(blockedDates().some(x=>x.date===selectedDate))return;let a=blocked();const i=a.findIndex(x=>x.date===selectedDate&&x.time===time);if(i>=0)a.splice(i,1);else a.push({date:selectedDate,time});localStorage.setItem(keyBlocked,JSON.stringify(a));renderDay()}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
document.querySelector('#datePicker').onchange=e=>{selectedDate=e.target.value;renderDay()};document.querySelector('#toggleDay').onclick=()=>{let a=blockedDates();const i=a.findIndex(x=>x.date===selectedDate);if(i>=0)a.splice(i,1);else a.push({date:selectedDate,reason:''});localStorage.setItem(keyDates,JSON.stringify(a));renderDay()};document.querySelector('#otherDay').onclick=()=>document.querySelector('#datePicker').showPicker?.();document.querySelector('#newBooking').onclick=()=>location.href='index.html#agendamento';
const sheet=document.querySelector('#sheet');document.querySelector('#blockTime').onclick=()=>{document.querySelector('#sheetDate').textContent=fmt(selectedDate);document.querySelector('#sheetTimes').innerHTML=times.map(t=>`<button class="${blocked().some(x=>x.date===selectedDate&&x.time===t)?'blocked':''}" onclick="toggleSlot('${t}');openSheet()">${t}</button>`).join('');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false')};function openSheet(){document.querySelector('#blockTime').click()}document.querySelector('#sheetClose').onclick=()=>{sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true')};sheet.onclick=e=>{if(e.target===sheet)document.querySelector('#sheetClose').click()};renderToday();renderDay();
