const services=['Corte','Barba','Combo','Pigmentação','Relaxamento','Pezinho','Luzes','Nevou'];
const serviceDurations=[30,30,30,30,30,30,60,30];
const times=['09:00','09:30','10:00','10:30','11:00','11:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00'];
const keyBookings='ms-bookings',keyBlocked='ms-blocked-slots',keyDates='ms-blocked-dates';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=d=>new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase();
const bookings=()=>JSON.parse(localStorage.getItem(keyBookings)||'[]');const blocked=()=>JSON.parse(localStorage.getItem(keyBlocked)||'[]');const blockedDates=()=>JSON.parse(localStorage.getItem(keyDates)||'[]');
const toMin=t=>{const[h,m]=t.split(':').map(Number);return h*60+m};const toTime=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function bookingIndexes(b){return Array.isArray(b.services)&&b.services.length?b.services:(Number.isInteger(b.service)?[b.service]:[])}
function bookingLabel(b){const names=bookingIndexes(b).map(i=>services[i]).filter(Boolean);return names.length?names.join(' + '):'Serviço'}
function bookingDuration(b){if(Number(b.totalDurationMinutes)>0)return Number(b.totalDurationMinutes);const ids=bookingIndexes(b);return ids.length?ids.reduce((sum,i)=>sum+(serviceDurations[i]||30),0):30}
function occupies(b,t){const s=toMin(b.time),e=s+bookingDuration(b),m=toMin(t);return m>=s&&m<e}
let selectedDate=today();
document.querySelector('#todayTitle').textContent=fmt(today());document.querySelector('#datePicker').value=selectedDate;
function renderToday(){const list=bookings().filter(x=>x.date===today()&&x.status!=='cancelled').sort((a,b)=>a.time.localeCompare(b.time));const now=new Date().toTimeString().slice(0,5);const next=list.find(x=>x.time>=now)||list[0];document.querySelector('#nextClient').innerHTML=next?`<div class="next-card"><small>PRÓXIMO CLIENTE</small><strong>${next.time} — ${esc(next.name)}</strong><p>${esc(bookingLabel(next))} · ${esc(next.phone)}</p></div>`:'';document.querySelector('#appointmentList').innerHTML=list.length?list.map(x=>`<div class="appointment"><time>${x.time}</time><div><strong>${esc(x.name)}</strong><small>${esc(bookingLabel(x))} · ${esc(x.phone)} · até ${toTime(toMin(x.time)+bookingDuration(x))}</small></div><div class="appointment-actions"><button class="done" onclick="setStatus('${x.createdAt}','completed')">Concluir</button><button class="cancel" onclick="setStatus('${x.createdAt}','cancelled')">Cancelar</button></div></div>`).join(''):'<div class="empty">Nenhum agendamento para hoje.</div>'}
function setStatus(id,status){const a=bookings();const x=a.find(v=>v.createdAt===id);if(x)x.status=status;localStorage.setItem(keyBookings,JSON.stringify(a));renderToday();renderDay()}
function renderDay(){const dayBookings=bookings().filter(x=>x.date===selectedDate&&x.status!=='cancelled');const dayBlocked=blocked().filter(x=>x.date===selectedDate).map(x=>x.time);const full=blockedDates().some(x=>x.date===selectedDate);document.querySelector('#dayState').innerHTML=full?'<div class="day-state">Você bloqueou este dia.</div>':'';const dayBtn=document.querySelector('#toggleDay');dayBtn.textContent=full?'DESBLOQUEAR DIA':'BLOQUEAR DIA INTEIRO';dayBtn.classList.toggle('active',full);document.querySelector('#slotList').innerHTML=times.map(t=>{const b=dayBookings.find(x=>occupies(x,t));const start=b&&b.time===t;const isBlocked=dayBlocked.includes(t)||full;const status=b?(start?`${esc(b.name)} · ${esc(bookingLabel(b))}`:`OCUPADO · até ${toTime(toMin(b.time)+bookingDuration(b))}`):isBlocked?'BLOQUEADO':'LIVRE';return `<div class="slot ${b?'booked':isBlocked?'blocked':''}"><time>${t}</time><div class="status">${status}</div>${!b&&!full?`<button onclick="toggleSlot('${t}')">${isBlocked?'Desbloquear':'Bloquear'}</button>`:''}</div>`}).join('')}
function toggleSlot(time){if(blockedDates().some(x=>x.date===selectedDate))return;let a=blocked();const i=a.findIndex(x=>x.date===selectedDate&&x.time===time);if(i>=0)a.splice(i,1);else a.push({date:selectedDate,time});localStorage.setItem(keyBlocked,JSON.stringify(a));renderDay()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
document.querySelector('#datePicker').onchange=e=>{selectedDate=e.target.value;renderDay()};document.querySelector('#toggleDay').onclick=()=>{let a=blockedDates();const i=a.findIndex(x=>x.date===selectedDate);if(i>=0)a.splice(i,1);else a.push({date:selectedDate,reason:''});localStorage.setItem(keyDates,JSON.stringify(a));renderDay()};document.querySelector('#otherDay').onclick=()=>document.querySelector('#datePicker').showPicker?.();document.querySelector('#newBooking').onclick=()=>location.href='index.html#servicos';
const sheet=document.querySelector('#sheet');document.querySelector('#blockTime').onclick=()=>{document.querySelector('#sheetDate').textContent=fmt(selectedDate);document.querySelector('#sheetTimes').innerHTML=times.map(t=>`<button class="${blocked().some(x=>x.date===selectedDate&&x.time===t)?'blocked':''}" onclick="toggleSlot('${t}');openSheet()">${t}</button>`).join('');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false')};function openSheet(){document.querySelector('#blockTime').click()}document.querySelector('#sheetClose').onclick=()=>{sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true')};sheet.onclick=e=>{if(e.target===sheet)document.querySelector('#sheetClose').click()};renderToday();renderDay();
